export type SelectProps = {
    label: string;
    placeholder: any;
    name: string;
    required: boolean;
    width: number;
    options?: Array<string> | Object;
    hasEmptyOption?: boolean;
    help?: string;
    hint?: string;
    disabled: boolean;
    multiple?: boolean;
    customError?: string;
    formTouched?: boolean;
    customErrorMessage?: string;
    onChange: (value: string) => void;
    value: string;
    className?: string;
    tabIndex: number;
    id: string;
};
declare const Select: (props: SelectProps) => import("react/jsx-runtime").JSX.Element;
export default Select;
